services:
  server:
    image: ghcr.io/bottle-nex/nocturn-server:latest
    container_name: nocturn-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SERVER_NODE_ENV=production

  orchestrator:
    image: ghcr.io/bottle-nex/nocturn-orchestrator:latest
    container_name: nocturn-orchestrator
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
