import './globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOption } from './api/auth/[...nextauth]/options';
import SessionSetter from '@/components/utility/SessionSetter';
import { Toaster } from 'sonner';
import { ThemeProvider } from 'next-themes';
import Providers from './providers';

export const metadata: Metadata = {
    title: 'Nocturn',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOption);
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider 
                    attribute="class" 
                    defaultTheme="dark"
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    <Toaster theme="dark" />
                    <Providers>{children}</Providers>
                    <SessionSetter session={session} />
                </ThemeProvider>
            </body>
        </html>
    );
}
