import './globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOption } from './api/auth/[...nextauth]/options';
import SessionSetter from '@/components/utility/SessionSetter';
import { ThemeProvider } from 'next-themes';
import ToasterProvider from '../src/providers/ToasterProvider';
import LenisProvider from '@/providers/LenisProvider';
import SubscriptionProvider from '@/providers/SubscriptionProvider';

export const metadata: Metadata = {
    title: 'Nocturn',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOption);
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <LenisProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem={false}
                        disableTransitionOnChange
                    >
                        <ToasterProvider />
                        <SubscriptionProvider>
                            {children}
                        </SubscriptionProvider>
                        <SessionSetter session={session} />
                    </ThemeProvider>
                </LenisProvider>
            </body>
        </html>
    );
}
