// Avatar images ship with the web app at apps/web/public/avatars.
const AVATAR_COUNT = 76;

const names = [
    'John Doe',
    'Jane Smith',
    'Michael Johnson',
    'Emily Davis',
    'David Brown',
    'Sarah Wilson',
    'James Miller',
    'Olivia Taylor',
    'Daniel Anderson',
    'Sophia Thomas',
    'William Moore',
    'Isabella Jackson',
    'Alexander White',
    'Ava Harris',
    'Benjamin Martin',
    'Mia Thompson',
    'Christopher Garcia',
    'Charlotte Martinez',
    'Matthew Robinson',
    'Amelia Clark',
    'Andrew Rodriguez',
    'Abigail Lewis',
    'Ethan Lee',
    'Harper Walker',
    'Jacob Hall',
    'Evelyn Allen',
    'Logan Young',
    'Lily Hernandez',
    'Noah King',
    'Chloe Wright',
    'Lucas Lopez',
    'Ella Scott',
    'Jack Green',
    'Grace Adams',
    'Owen Baker',
    'Zoey Nelson',
    'Henry Hill',
    'Layla Carter',
    'Sebastian Mitchell',
    'Aria Perez',
    'Julian Roberts',
    'Nora Turner',
    'Leo Phillips',
    'Riley Campbell',
    'Nathan Parker',
    'Lillian Evans',
    'Aaron Edwards',
    'Hannah Collins',
    'Caleb Stewart',
    'Ellie Sanchez',
    'Isaac Morris',
    'Scarlett Rogers',
    'Ryan Reed',
    'Victoria Cook',
    'Dylan Morgan',
    'Penelope Bell',
    'Christian Murphy',
    'Zoe Bailey',
    'Elijah Rivera',
    'Lucy Cooper',
    'Gabriel Richardson',
    'Paisley Cox',
    'Anthony Howard',
    'Naomi Ward',
    'Charles Peterson',
    'Hazel Gray',
    'Thomas Hughes',
    'Aubrey Ramirez',
    'Joshua Price',
    'Stella James',
    'Lincoln Wood',
    'Savannah Bennett',
    'Adam Barnes',
    'Brooklyn Ross',
    'Nathaniel Henderson',
    'Kinsley Coleman',
    'Isaiah Jenkins',
    'Maya Perry',
    'Hunter Powell',
    'Skylar Long',
    'Dominic Patterson',
    'Elena Hughes',
    'Jonathan Flores',
    'Piper Washington',
    'Jeremiah Butler',
    'Aaliyah Simmons',
    'Adrian Foster',
    'Claire Bryant',
    'Brayden Alexander',
    'Camila Russell',
    'Jaxon Griffin',
    'Audrey Diaz',
    'Levi Hayes',
    'Anna Myers',
    'Jason Ford',
    'Caroline Hamilton',
    'Evan Graham',
    'Madelyn Sullivan',
    'Miles Wallace',
    'Sophie West',
];

const colors = [
    '#FF5733',
    '#33FF57',
    '#3357FF',
    '#FF33A1',
    '#A133FF',
    '#33FFF6',
    '#FF8C33',
    '#8CFF33',
    '#338CFF',
    '#FF3380',
    '#8033FF',
    '#33FFF0',
    '#FF6633',
    '#66FF33',
    '#3366FF',
    '#FF3366',
    '#6633FF',
    '#33FFF3',
];
export default class GenerateUser {
    static getRandomAvatar() {
        return `/avatars/avatar-${Math.floor(Math.random() * AVATAR_COUNT) + 1}.png`;
    }

    static getRandomName() {
        const position = Math.floor(Math.random() * names.length);
        return names[position] as string;
    }

    static getRandomColorsForCollaborators() {
        const position = Math.floor(Math.random() * colors.length);
        return colors[position] as string;
    }
}
