export enum QuizStatusEnum {
  CREATED = "CREATED",
  PUBLISHED = "PUBLISHED",
  SCHEDULED = "SCHEDULED",
  LIVE = "LIVE",
  COMPLETED = "COMPLETED",
  TIMED_OUT = "TIMED_OUT",
  CANCELLED = "CANCELLED",
  PAYOUT_PENDING = "PAYOUT_PENDING",
  PAYOUT_COMPLETED = "PAYOUT_COMPLETED",
  NULL = "NULL",
}

export enum InteractionEnum {
  THUMBS_UP = "THUMBS_UP",
  DOLLAR = "DOLLAR",
  BULB = "BULB",
  HEART = "HEART",
  SMILE = "SMILE",
}

export enum SessionStatusEnum {
  WAITING = "WAITING",
  LIVE = "LIVE",
  COMPLETED = "COMPLETED",
  PAUSED = "PAUSED",
  TIMED_OUT = "TIMED_OUT",
}

export enum ParticipantScreenEnum {
  LOBBY = "LOBBY",
  COUNTDOWN = "COUNTDOWN",
  QUESTION_MOTIVATION = "QUESTION_MOTIVATION",
  QUESTION_READING = "QUESTION_READING",
  QUESTION_ACTIVE = "QUESTION_ACTIVE",
  QUESTION_RESULTS = "QUESTION_RESULTS",
  QUIZ_RESULTS = "QUIZ_RESULTS",
}

export enum SpectatorScreenEnum {
  LOBBY = "LOBBY",
  COUNTDOWN = "COUNTDOWN",
  QUESTION_MOTIVATION = "QUESTION_MOTIVATION",
  QUESTION_READING = "QUESTION_READING",
  QUESTION_ACTIVE = "QUESTION_ACTIVE",
  QUESTION_RESULTS = "QUESTION_RESULTS",
  QUIZ_RESULTS = "QUIZ_RESULTS",
}

export enum HostScreenEnum {
  LOBBY = "LOBBY",
  QUESTION_PREVIEW = "QUESTION_PREVIEW",
  QUESTION_READING = "QUESTION_READING",
  QUESTION_ACTIVE = "QUESTION_ACTIVE",
  QUESTION_RESULTS = "QUESTION_RESULTS",
  LEADERBOARD = "LEADERBOARD",
  FINAL_RESULTS = "FINAL_RESULTS",
  QUIZ_RESULTS = "QUIZ_RESULTS",
}

export enum USER_TYPE {
  HOST = "HOST",
  PARTICIPANT = "PARTICIPANT",
  SPECTATOR = "SPECTATOR",
}

export enum QuizPhaseEnum {
  QUESTION_READING = "QUESTION_READING",
  QUESTION_ACTIVE = "QUESTION_ACTIVE",
  SHOW_RESULTS = "SHOW_RESULTS",
  WAITING_NEXT = "WAITING_NEXT",
}

export enum CollabRole {
  HOST = "HOST",
  EDITOR = "EDITOR",
  VIEWER = "VIEWER",
}

export enum AgentStep {
  START = "START",
  ASK_DIFFICULTY = "ASK_DIFFICULTY",
  WAIT_DIFFICULTY = "WAIT_DIFFICULTY",
  PLANNING = "PLANNING",
  GENERATE = "GENERATE",
  REVISE = "REVISE",
  DONE = "DONE",
  CANCELLED = "CANCELLED",
  ACCEPTED = "ACCEPTED",
}

export enum AiQuizChatRole {
  SYSTEM = "SYSTEM",
  AGENT = "AGENT",
  USER = "USER",
}

export enum AiMessageElement {
  DIFFICULTY = "DIFFICULTY",
  TITLE = "TITLE",
  QUIZ = "QUIZ",
}

export enum QuizEndScreen {
  ARE_YOU_UP = "ARE_YOU_UP",
  READY_TO_ANNOUNCE = "READY_TO_ANNOUNCE",
  ANNOUNCED = "ANNOUNCED",
}

export enum TemplateEnum {
  CLASSIC = "CLASSIC",
  MODERN = "MODERN",
  NEON = "NEON",
  YELLOW = "YELLOW",
  GREEN = "GREEN",
  PASTEL = "PASTEL",
  BLUE = "BLUE",
}

export enum SubscriptionEnum {
  FREE = "FREE",
  PRO = "PRO",
}

export enum ClaimStatusEnum {
  PENDING = "PENDING",
  CLAIMED = "CLAIMED",
  EXPIRED = "EXPIRED",
  REFUNDED = "REFUNDED",
}
