export enum SidebarTab {
    HOME = 'HOME',
    SHARED_WITH_ME = 'SHARED_WITH_ME',
    MY_PRESENTATIONS = 'MY_PRESENTATIONS',

    FAVORITES = 'FAVORITES',
    SETTINGS = 'SETTINGS',
    TRASH = 'TRASH',
    CHATS = 'CHATS',
}
