export enum LIMIT_TYPE {
  NUMERIC = "NUMERIC",
  BOOLEAN = "BOOLEAN",
  RATE = "RATE",
}

export enum FEATURE {
  MAX_PARTICIPANTS_PER_SESSION = "MAX_PARTICIPANTS_PER_SESSION",
  MAX_SPECTATORS_PER_SESSION = "MAX_SPECTATORS_PER_SESSION",
  MAX_COLLABORATORS_PER_SESSION = "MAX_COLLABORATORS_PER_SESSION",
  MAX_SLIDES_PER_PRESENTATION = "MAX_SLIDES_PER_PRESENTATION",
  MAX_CONCURRENT_SESSIONS = "MAX_CONCURRENT_SESSIONS",
  LIVE_CHAT = "LIVE_CHAT",
  SESSIONS_PER_DAY = "SESSIONS_PER_DAY",
}
